import type {
  AiApiSource as SharedAiApiSource,
  CycleOrigin as SharedCycleOrigin,
  AgentAvailability as SharedAgentAvailability,
  AssignmentEndReason as SharedAssignmentEndReason,
  AssignmentStartReason as SharedAssignmentStartReason,
  ConversationCloseReason as SharedConversationCloseReason,
  ConversationStatus as SharedConversationStatus,
  AiHandoffReason as SharedAiHandoffReason,
  AiRunResult as SharedAiRunResult,
  AiTaskStatus as SharedAiTaskStatus,
  AiTone as SharedAiTone,
  ConversationChannel as SharedConversationChannel,
  MessageDeliveryStatus as SharedMessageDeliveryStatus,
  WebhookEventStatus as SharedWebhookEventStatus,
  WhatsAppAccountStatus as SharedWhatsAppAccountStatus,
  ContactSource as SharedContactSource,
  ContactStatus as SharedContactStatus,
  ConversationMode as SharedConversationMode,
  MessageDirection as SharedMessageDirection,
  MessageSenderType as SharedMessageSenderType,
  CompanyStatus as SharedCompanyStatus,
  GlobalRole as SharedGlobalRole,
  MemberRole as SharedMemberRole,
  UserStatus as SharedUserStatus,
  SettingsPermission as SharedSettingsPermission,
  ScheduleOverride as SharedScheduleOverride,
} from "@arthur-ai/shared";
import type {
  AiApiSource,
  CycleOrigin,
  AgentAvailability,
  AssignmentEndReason,
  AssignmentStartReason,
  ConversationCloseReason,
  ConversationStatus,
  AiHandoffReason,
  AiRunResult,
  AiTaskStatus,
  AiTone,
  CompanyStatus,
  ContactSource,
  ContactStatus,
  ConversationChannel,
  ConversationMode,
  MessageDeliveryStatus,
  WebhookEventStatus,
  WhatsAppAccountStatus,
  GlobalRole,
  MemberRole,
  MessageDirection,
  MessageSenderType,
  UserStatus,
  SettingsPermission,
  ScheduleOverride,
} from "./generated/prisma/client.js";

// Falha o typecheck se os enums do Prisma e do pacote shared divergirem.
type Equals<A, B> = [A] extends [B] ? ([B] extends [A] ? true : false) : false;
type Assert<T extends true> = T;

export type EnumParity = [
  Assert<Equals<GlobalRole, SharedGlobalRole>>,
  Assert<Equals<UserStatus, SharedUserStatus>>,
  Assert<Equals<CompanyStatus, SharedCompanyStatus>>,
  Assert<Equals<MemberRole, SharedMemberRole>>,
  Assert<Equals<ContactStatus, SharedContactStatus>>,
  Assert<Equals<ContactSource, SharedContactSource>>,
  Assert<Equals<ConversationMode, SharedConversationMode>>,
  Assert<Equals<MessageDirection, SharedMessageDirection>>,
  Assert<Equals<MessageSenderType, SharedMessageSenderType>>,
  Assert<Equals<ConversationChannel, SharedConversationChannel>>,
  Assert<Equals<MessageDeliveryStatus, SharedMessageDeliveryStatus>>,
  Assert<Equals<WhatsAppAccountStatus, SharedWhatsAppAccountStatus>>,
  Assert<Equals<WebhookEventStatus, SharedWebhookEventStatus>>,
  Assert<Equals<AiTone, SharedAiTone>>,
  Assert<Equals<AiHandoffReason, SharedAiHandoffReason>>,
  Assert<Equals<AiTaskStatus, SharedAiTaskStatus>>,
  Assert<Equals<AiRunResult, SharedAiRunResult>>,
  Assert<Equals<AgentAvailability, SharedAgentAvailability>>,
  Assert<Equals<ConversationStatus, SharedConversationStatus>>,
  Assert<Equals<ConversationCloseReason, SharedConversationCloseReason>>,
  Assert<Equals<AssignmentStartReason, SharedAssignmentStartReason>>,
  Assert<Equals<AssignmentEndReason, SharedAssignmentEndReason>>,
  Assert<Equals<AiApiSource, SharedAiApiSource>>,
  Assert<Equals<CycleOrigin, SharedCycleOrigin>>,
  Assert<Equals<SettingsPermission, SharedSettingsPermission>>,
  Assert<Equals<ScheduleOverride, SharedScheduleOverride>>,
];
